title: "Trevorion Weekly Anime/AI RSS Feed"
description: "A weekly digest of anime AI dailies, news, comics, and articles."
baseurl: ""
url: "https://rss.trevorion.io"
tags:
  - AI
  - Anime
  - News
  - Articles
  - DailyImage
  - AnimeAI
  - AIArt
  - WeeklyDigest
  - Comics
  - Trevorion
  - AnimeStyle
  - Highlights
markdown: kramdown
#exclude:
#  - feed.xml
# plugins:
#   - jekyll-feed
