title: "Trevorion Anime/AI RSS Feed"
description: "A weekly digest of anime AI dailies, news, comics, and articles."
baseurl: ""
url: "https://rss.trevorion.io"
home_url: "https://trevorion.io"
rss_url: "https://rss.trevorion.io/feed.xml"
full_rss: "https://rss.trevorion.io/full-feed.xml"
rss_tags:
  - AI
  - Anime
  - News
  - Articles
  - DailyImage
  - AnimeAI
  - AIArt
  - WeeklyDigest
  - Comics
  - Trevorion
  - AnimeStyle
  - Highlights
markdown: kramdown
#exclude:
#  - feed.xml
# plugins:
#   - jekyll-feed
