title: "Trevorion Weekly Feed"
description: "A weekly digest of anime AI dailies, memes, polls, and articles."
baseurl: ""
url: "https://rss.trevorion.io"
markdown: kramdown
#exclude:
#  - feed.xml
# plugins:
#   - jekyll-feed
