name: Backfill All Monthly Digests

on:
  workflow_dispatch:

jobs:
  run-backfill:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Run backfill script
        run: python scripts/generate_all_monthlies.py

      - name: Commit and push monthly digests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add _monthly/
          git diff --cached --quiet || git commit -m "Backfill all monthly digests"
          git push --force-with-lease origin HEAD
