name: Backfill All Monthly Digests

on:
  workflow_dispatch:

jobs:
  run-backfill:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Extract day → title/url map
        run: python scripts/extract_day_map.py
        
      - name: Commit and Push Updated Day Map
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add scripts/day_url_map_full_with_titles.py
          git commit -m "Auto-update day_url_map_full_with_titles.py" || echo "No changes to commit"
          git push --force-with-lease origin HEAD

      - name: Pull to ensure workspace is latest
        run: git pull --rebase

      - name: Generate Monthly Digests
        run: python scripts/generate_all_monthlies.py

      - name: Commit and push monthly digests
        run: |
          git add monthly/
          git commit -m "Backfill monthly digests" || echo "No changes to commit"
          git push --force-with-lease origin HEAD

      - name: Pull to ensure workspace is latest
        run: git pull --rebase
