name: Extract Tweet Images

on:
  workflow_dispatch:

jobs:
  extract-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install requests

      - name: Run extract_tweet_images.py
        run: python scripts/extract_tweet_images.py

      - name: Commit and push new image list files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add gallery/
          git commit -m "Auto-generate tweet image lists" || echo "No changes to commit"
          git pull --rebase
          git push --force-with-lease origin HEAD
