name: Fetch Monthly Tweet Images

on:
  workflow_dispatch:

jobs:
  fetch-monthly-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Tweepy
        run: pip install tweepy

      - name: Run fetch_monthly_images.py
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
        run: python scripts/fetch_monthly_images.py

      - name: Commit and push gallery files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add gallery/
          git commit -m "Auto-update monthly tweet gallery files" || echo "No changes to commit"
          git pull --rebase
          git push --force-with-lease origin HEAD
