name: Fetch Tweet Details

on:
  workflow_dispatch:

jobs:
  fetch-tweet-details:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          
      - name: Install requests
        run: pip install requests
      
      - name: Run fetch_tweet_v2.py
        env:
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
        run: python scripts/fetch_tweet_v2.py
