name: Update archive.md

on:
  push:
    paths:
      - "_posts/**"

jobs:
  update-archive:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Run archive updater
        run: python scripts/update_archive.py

      - name: Commit and push archive.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add archive.md
          git diff --cached --quiet || git commit -m "Auto-update archive.md"
          n=0
          until git pull --rebase && git push --force-with-lease origin HEAD; do
            n=$((n+1))
            if [ $n -ge 5 ]; then
              echo "Failed to push after 5 attempts"
              exit 1
            fi
            sleep 5
          done

      - name: Pull to ensure workspace is latest
        run: git pull --rebase
