name: Update index.md

on:
  push:
    paths:
      - "_posts/**"

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Run index updater
        run: python scripts/update_index.py

      - name: Commit and push index.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add index.md
          git diff --cached --quiet || git commit -m "Auto-update index.md"
          git pull origin HEAD --rebase
          git push --force-with-lease origin HEAD
