name: Update archive.md

on:
  push:
    paths:
      - "_posts/**"

jobs:
  update-archive:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3
      with:
        persist-credentials: true  # REQUIRED to allow git push

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Run archive updater script
      run: python scripts/update_archive.py

    - name: Commit and push archive.md
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add archive.md
        git commit -m "Update archive.md automatically" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
